# Generated by Django 6.0.3 on 2026-05-16 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeanalysis',
            name='code_smells',
        ),
        migrations.RemoveField(
            model_name='codeanalysis',
            name='errors_detected',
        ),
        migrations.RemoveField(
            model_name='codeanalysis',
            name='oop_concepts',
        ),
        migrations.RemoveField(
            model_name='codeanalysis',
            name='refactoring_suggestions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_analyses',
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_entry', to='analyzer.codeanalysis'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AnalysisError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors_detected', to='analyzer.codeanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='CodeSmell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smell_type', models.CharField(max_length=100)),
                ('detected_value', models.CharField(blank=True, max_length=255)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('suggestion', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_smells', to='analyzer.codeanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='OOPConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_name', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oop_concepts', to='analyzer.codeanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='RefactoringSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(default='medium', max_length=50)),
                ('suggestion_text', models.TextField()),
                ('refactored_code', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refactoring_suggestions', to='analyzer.codeanalysis')),
            ],
        ),
    ]
