# Generated by Django 6.0.3 on 2026-05-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_remove_codeanalysis_code_smells_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeanalysis',
            name='analysis_number',
            field=models.IntegerField(default=1),
        ),
    ]
