# Generated by Django 6.0.3 on 2026-05-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_codeanalysis_analysis_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('ultra', 'Ultra')], default='free', max_length=20),
        ),
    ]
